# Generated by Django 5.1.7 on 2025-03-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingtask',
            name='email_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='email_subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='email_to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
