# Generated by Django 5.1.7 on 2025-03-23 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_onboardingtask_email_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingtask',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or instructions for this task', null=True),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='onboardingtask',
            name='job_types',
            field=models.ManyToManyField(blank=True, to='employees.jobtype'),
        ),
        migrations.AlterField(
            model_name='onboardingtask',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
