# Generated by Django 5.1.7 on 2025-03-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_onboardingtask_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingtask',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Onboarding Task', 'verbose_name_plural': 'Onboarding Tasks'},
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which this task should appear'),
        ),
    ]
